import test from "node:test";
import assert from "node:assert/strict";
import { refreshPackages, absoluteIndexUrl } from "../src/sync.js";

const h="b".repeat(64); const packageManifest={schema_version:1,post_id:"p",brand:"atlet",content_revision:"r",exported_at:"2026-09-25T10:00:00Z",channel:"instagram",files:[{name:"x.mp4",sha256:h},{name:"opis-do-skopiowania.txt",sha256:h},{name:"hashtagi.txt",sha256:h}]};
test("offline zgłasza błąd i nie mutuje ostatniego poprawnego odczytu", async()=>{ const existing=[packageManifest]; await assert.rejects(refreshPackages({indexUrl:"https://drive.test/index.json",brand:"atlet",existing,fetcher:async()=>{throw Error("offline")}}),/offline/); assert.equal(existing.length,1); assert.equal(existing[0].content_revision,"r"); });
test("pobiera indeks i manifest względny", async()=>{ const fetcher=async url=>({ok:true,json:async()=>String(url).endsWith("index.json")?{packages:[{brand:"atlet",manifest_url:"p/manifest.json"}]}:packageManifest}); const result=await refreshPackages({indexUrl:"https://drive.test/index.json",brand:"atlet",existing:[],fetcher}); assert.equal(result.manifests.length,1); });
test("domyślny adres paczek jest względny do aplikacji na Hostingerze", ()=>{ assert.equal(absoluteIndexUrl("", "https://example.com/publikacje/"), "https://example.com/publikacje/paczki/index.json"); assert.equal(absoluteIndexUrl("paczki/index.json", "https://example.com/publikacje/index.html"), "https://example.com/publikacje/paczki/index.json"); assert.equal(absoluteIndexUrl("https://cdn.test/i.json", "https://example.com/"), "https://cdn.test/i.json"); });
test("manifest z adresu względnego rozwiązuje się względem strony", async()=>{ globalThis.location={href:"https://example.com/publikacje/"}; const seen=[]; const fetcher=async url=>{seen.push(String(url));return {ok:true,json:async()=>String(url).endsWith("index.json")?{packages:[{brand:"atlet",manifest_url:"atlet/do-instagrama/p-1/manifest.json"}]}:packageManifest}}; try{ const r=await refreshPackages({indexUrl:"paczki/index.json",brand:"atlet",existing:[],fetcher}); assert.equal(seen[1],"https://example.com/publikacje/paczki/atlet/do-instagrama/p-1/manifest.json"); assert.equal(r.manifests[0]._manifest_url,seen[1]); } finally { delete globalThis.location; } });
test("stare puste ustawienia dostają domyślny adres paczek", async()=>{ const { createStore } = await import("../src/store.js"); const mem=new Map([["byku.mobile.settings.v1",JSON.stringify({brand:"rigger",indexUrl:""})]]); const store=createStore({getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,v)}); assert.deepEqual(store.settings(),{brand:"rigger",indexUrl:"paczki/index.json"}); });
test("zablokowana pamięć przeglądarki nie wywraca aplikacji", async()=>{ const { createStore } = await import("../src/store.js"); const store=createStore({getItem(){throw Error("SecurityError")},setItem(){throw Error("QuotaExceeded")}}); assert.deepEqual(store.settings(),{brand:"atlet",indexUrl:"paczki/index.json"}); assert.doesNotThrow(()=>store.saveEvents([{event_id:"e"}])); });
