const state={hostinger:{},cards:[],selected:null,brand:'atlet',filter:'action',channel:'instagram',view:'today',tab:'preview'};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const I=p=>`<svg viewBox="0 0 24 24" aria-hidden="true">${p}</svg>`;
const ICONS={
  today:I('<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 1v3M12 20v3M1 12h3M20 12h3"/>'),
  finish:I('<path d="M4 20h4L19 9l-4-4L4 16z"/><path d="m13 7 4 4"/>'),
  library:I('<path d="M3 4h7v7H3zM14 4h7v7h-7zM3 15h7v5H3zM14 15h7v5h-7z"/>'),
  calendar:I('<path d="M3 6h18v15H3zM3 11h18M8 3v5M16 3v5"/>'),
  publications:I('<path d="M5 4v16l15-8z"/>'),
  style:I('<path d="M4 19 10 5l6 14M6.5 14h7M16 19h5"/>'),
  learning:I('<path d="M12 3 2 8l10 5 10-5z"/><path d="M6 10.5V16c3 2.5 9 2.5 12 0v-5.5"/>'),
  archive:I('<path d="M3 4h18v5H3zM5 9v11h14V9M10 13h4"/>')
};
const NAV=[['today','Dzisiaj'],['finish','Do dokończenia'],['library','Biblioteka'],['calendar','Kalendarz'],['publications','Publikacje'],['style','Opisy i styl'],['learning','Uczenie'],['archive','Archiwum']];
const CH=[['tiktok','TikTok','TT'],['instagram','Instagram','IG'],['facebook','Facebook','FB']];
const DAYS=['NDZ','PON','WT','ŚR','CZW','PT','SOB'];
const pad=n=>String(n).padStart(2,'0');
const brandMatch=x=>state.brand==='all'||x.brand===state.brand;
const isRunning=x=>Object.values(x.channels).some(c=>['running','awaiting_user'].includes(c.delivery));
const needsReview=x=>Object.values(x.channels).some(c=>c.platform_evidence!=='unknown'&&!c.manual_checked);
function when(s){if(!s)return null;const d=new Date(String(s).replace(' ','T'));return isNaN(d)?null:d}

let toastTimer;
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3400)}
async function api(path,opt={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opt});const d=await r.json();if(!r.ok)throw Object.assign(new Error(d.error||'Operacja nie powiodła się'),{status:r.status,data:d});return d}

function nav(){$('#nav').innerHTML=NAV.map(([id,n],i)=>`<button data-view="${id}" class="${state.view===id?'active':''}" title="${n}"><span class="idx">${pad(i+1)}</span>${ICONS[id]}<span>${n}</span></button>`).join('');$('#nav').onclick=e=>{const b=e.target.closest('button');if(!b)return;state.view=b.dataset.view;state.filter=state.view==='archive'?'all':state.view==='finish'?'finish':'action';nav();render();};}
function brandSeg(){document.querySelectorAll('#brandSeg button').forEach(b=>b.setAttribute('aria-checked',String(b.dataset.brand===state.brand)))}

function label(ch){const e=ch.platform_evidence,d=ch.delivery;if(d==='running')return['W toku','running'];if(d==='awaiting_user')return['Czeka na Ciebie','awaiting_user'];if(d==='failed'||e==='failed')return['Błąd','failed'];if(e==='published')return[ch.manual_checked?'Opublikowany ✓':'Wykryto publikację','published'];if(e==='scheduled')return[ch.manual_checked?'Zaplanowany ✓':'Wykryto w kalendarzu','scheduled'];if(ch.manual_checked)return['Haczyk bez dowodu','checked'];if(ch.legacy_state==='wyslany')return['Wysłano — sprawdź','awaiting_user'];return['Czeka','idle']}
const TONE={publish:'hot',phone_package:'hot',diagnose:'bad',finish:'warn',review_content:'warn',manual_check:'warn',verify:'warn',schedule:'warn',show_progress:'info',done:'ok',show_history:''};
const STATUS_TONE={scheduled:'var(--blue)',published:'var(--green)',checked:'var(--green)',failed:'var(--red)',running:'var(--amber)',awaiting_user:'var(--amber)',idle:'var(--line-2)'};

function filtered(){let xs=state.cards.filter(brandMatch);if(state.view==='archive')return xs.filter(x=>x.archived);xs=xs.filter(x=>!x.archived);if(state.filter==='action')xs=xs.filter(x=>!['done'].includes(x.next_action.code));if(state.filter==='finish')xs=xs.filter(x=>['finish','review_content'].includes(x.next_action.code));if(state.filter==='phone')xs=xs.filter(x=>x.phone_ready);if(state.filter==='running')xs=xs.filter(isRunning);if(state.filter==='review')xs=xs.filter(needsReview);if(state.filter==='completed')xs=xs.filter(x=>x.next_action.code==='done');const q=$('#search').value.trim().toLowerCase();return q?xs.filter(x=>(x.name+' '+x.post_id).toLowerCase().includes(q)):xs}

function countUp(el){const to=+el.dataset.to;if(matchMedia('(prefers-reduced-motion: reduce)').matches||!to){el.textContent=to;return}const t0=performance.now(),dur=650;const step=t=>{const k=Math.min(1,(t-t0)/dur);el.textContent=Math.round(to*(1-Math.pow(1-k,3)));if(k<1)requestAnimationFrame(step)};requestAnimationFrame(step)}
function renderSummary(){const xs=state.cards.filter(x=>!x.archived&&brandMatch(x));const total=Math.max(1,xs.length);const vals=[['action','Do działania',xs.filter(x=>x.next_action.code!=='done').length,'hot'],['phone','Na telefon',xs.filter(x=>x.next_action.code==='phone_package').length,''],['running','W toku',xs.filter(isRunning).length,'info'],['review','Do sprawdzenia',xs.filter(needsReview).length,'warn'],['archive','Archiwum',state.cards.filter(x=>x.archived&&brandMatch(x)).length,'']];$('#summary').innerHTML=vals.map(([id,n,v,tone],i)=>`<button class="metric ${tone} ${state.filter===id?'on':''}" data-filter="${id}"><span class="code">M-${pad(i+1)}</span><strong data-to="${v}">0</strong><span>${n}</span><div class="bar"><i style="width:${id==='archive'?0:Math.round(v/total*100)}%"></i></div></button>`).join('');$('#summary').querySelectorAll('strong[data-to]').forEach(countUp);$('#summary').onclick=e=>{const b=e.target.closest('.metric');if(!b)return;if(b.dataset.filter==='archive'){state.view='archive';state.filter='all';nav();return render()}state.filter=b.dataset.filter;renderSummary();renderFilters();renderRows()}}
function renderFilters(){const base=state.cards.filter(x=>!x.archived&&brandMatch(x));const n={action:base.filter(x=>x.next_action.code!=='done').length,finish:base.filter(x=>['finish','review_content'].includes(x.next_action.code)).length,phone:base.filter(x=>x.phone_ready).length,running:base.filter(isRunning).length,review:base.filter(needsReview).length,completed:base.filter(x=>x.next_action.code==='done').length,all:base.length};const fs=[['action','Do działania'],['finish','Braki i opis'],['phone','Do telefonu'],['running','W trakcie'],['review','Do sprawdzenia'],['completed','Zakończone'],['all','Wszystkie']];$('#filters').innerHTML=state.view==='archive'?'':fs.map(([id,t])=>`<button class="filter ${state.filter===id?'active':''}" data-filter="${id}">${t}<b>${n[id]}</b></button>`).join('');$('#filters').onclick=e=>{const b=e.target.closest('button');if(b){state.filter=b.dataset.filter;renderFilters();renderSummary();renderRows()}}}

function relTime(s){const d=when(s);if(!d)return{cls:'none',txt:'Bez terminu',rel:''};const m=Math.round((d-Date.now())/60000);const txt=`${DAYS[d.getDay()]} ${pad(d.getDate())}.${pad(d.getMonth()+1)} · ${pad(d.getHours())}:${pad(d.getMinutes())}`;if(m<0)return{cls:'late',txt,rel:m>-1440?`${Math.floor(-m/60)} h ${-m%60} min temu`:'po terminie'};if(m<=15)return{cls:'hot',txt,rel:`T−${m} min`};if(m<180)return{cls:'soon',txt,rel:`za ${Math.floor(m/60)} h ${m%60} min`};if(m<1440)return{cls:'',txt,rel:`za ${Math.floor(m/60)} h`};return{cls:'',txt,rel:`za ${Math.round(m/1440)} d`}}
function thumbHtml(c){const img=c.assets.thumbnail_url?`<img class="thumb" src="${esc(c.assets.thumbnail_url)}" alt="Miniatura ${esc(c.name)}" loading="lazy">`:`<div class="thumb missing">Brak<br>miniaturki</div>`;return `<span class="frame">${img}</span>`}
function row(c,i){const t=relTime(c.local_target_at);const statuses=CH.map(([k])=>{const [txt,cl]=label(c.channels[k]);return `<div><span class="status ${cl}">${esc(txt)}</span><small class="meta">${esc(c.channels[k].platform_target_at||'')}</small></div>`}).join('');const code=c.next_action.code;const btn=['publish','phone_package'].includes(code)?'primary':code==='done'?'done':'';return `<article class="row ${state.selected===c.post_id?'selected':''} ${t.cls==='hot'?'imminent':''}" data-id="${esc(c.post_id)}" data-tone="${TONE[code]||''}" style="--i:${Math.min(i,14)}"><div class="material">${thumbHtml(c)}<div><b>${esc(c.name)}</b><div class="chips"><span class="chip ${esc(c.brand)}">${esc(c.brand.toUpperCase())}</span><span class="chip">${c.assets.type==='carousel'?'Karuzela':'Rolka'}</span></div><span class="when ${t.cls}">${esc(t.txt)}${t.rel?` <em>${esc(t.rel)}</em>`:''}</span></div></div>${statuses}<div class="next"><button class="${btn}">${esc(c.next_action.label)}</button><small class="meta">${esc(c.next_action.reason)}</small></div></article>`}
function renderRows(){const xs=filtered();$('#rows').innerHTML=xs.length?xs.map(row).join(''):'<div class="loading">Brak publikacji w tym widoku. Czysto.</div>';$('#rows').onclick=e=>{const r=e.target.closest('.row');if(r)select(r.dataset.id)}}
function select(id){state.selected=id;state.tab='preview';document.querySelectorAll('#rows .row').forEach(r=>r.classList.toggle('selected',r.dataset.id===id));renderDetail()}

function renderDetail(){const c=state.cards.find(x=>x.post_id===state.selected),d=$('#detail');if(!c){d.classList.remove('open');d.innerHTML='<div class="empty"><b>Wybierz publikację</b><span>Zobaczysz materiał, treść, kanały i historię.</span></div>';return}d.classList.add('open');const t=relTime(c.local_target_at);const strip=CH.map(([k,,short])=>{const [txt,cl]=label(c.channels[k]);return `<div style="--tone:${STATUS_TONE[cl]}"><small>${short}</small><span class="status ${cl}">${esc(txt)}</span></div>`}).join('');d.innerHTML=`<button class="close" id="closeDetail" aria-label="Zamknij panel">×</button><div class="detail-top">${thumbHtml(c)}<div><h2>${esc(c.name)}</h2><span class="badge ${esc(c.brand)}">${esc(c.brand.toUpperCase())}</span><span class="badge">${esc(c.assets.type==='carousel'?'Karuzela':'Rolka')}</span><span class="when ${t.cls}">${esc(t.txt)}${t.rel?` <em>${esc(t.rel)}</em>`:''}</span><span class="id">${esc(c.post_id)}</span></div></div><div class="strip">${strip}</div><div class="tabs">${[['preview','Podgląd'],['content','Treść'],['publish','Publikowanie'],['history','Historia']].map(([id,n])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}">${n}</button>`).join('')}</div><div class="panel" id="panel"></div>`;$('#closeDetail').onclick=closeDetail;d.querySelector('.tabs').onclick=e=>{const b=e.target.closest('button');if(b){state.tab=b.dataset.tab;renderDetail()}};renderPanel(c)}
function renderPanel(c){const p=$('#panel');if(state.tab==='preview'){const missing=c.assets.missing.join(', ');p.innerHTML=`<p>${esc(c.content.description||'Brak opisu')}</p><div class="facts"><div class="field"><span>Termin lokalny</span><b>${esc(c.local_target_at||'Nie ustawiono')}</b></div><div class="field"><span>Braki</span><b class="${missing?'warn':'ok'}">${esc(missing||'Paczka kompletna')}</b></div></div><div class="actions"><button class="ghost" id="folder">Otwórz folder</button><button class="action" id="primary">${esc(c.next_action.label)} →</button></div>`;$('#folder').onclick=()=>post(`/api/open-folder`,{post_id:c.post_id});$('#primary').onclick=()=>primary(c);}
if(state.tab==='content'){p.innerHTML=`<label class="field"><span>Opis</span><textarea id="description">${esc(c.content.description)}</textarea><small class="count" id="descCount"></small></label><label class="field"><span>Hashtagi</span><textarea id="hashtags" style="min-height:76px">${esc(c.content.hashtags)}</textarea></label><label class="field"><span>Lokalizacja</span><input id="location" value="${esc(c.content.location)}"></label><div class="actions"><button class="ghost" id="save">Zapisz tę wersję</button><button class="action" id="approve">Zapisz i zaakceptuj</button></div><small class="meta">Zapis produkcyjny jest dostępny dopiero po bezpiecznym przełączeniu właściciela magazynu.</small>`;const cnt=()=>$('#descCount').textContent=`${$('#description').value.length} ZNAKÓW`;$('#description').oninput=cnt;cnt();$('#save').onclick=()=>saveContent(c,false);$('#approve').onclick=()=>saveContent(c,true)}
if(state.tab==='publish'){p.innerHTML=CH.map(([k,n])=>{const [t,cl]=label(c.channels[k]);return `<div class="channel-line"><b>${n}</b><span class="status ${cl}">${esc(t)}</span><small>Dowód: ${esc(c.channels[k].platform_evidence)} · haczyk użytkownika: ${c.channels[k].manual_checked?'tak':'nie'}</small><button class="ghost prepare" data-channel="${k}">Przygotuj ${k}</button><button class="ghost manual" data-channel="${k}" data-checked="${c.channels[k].manual_checked?'false':'true'}">${c.channels[k].manual_checked?'Cofnij mój haczyk':'Potwierdzam wykonanie'}</button></div>`}).join('')+`<div class="actions" style="margin-top:16px"><button class="action" id="phone">Paczka na telefon</button><button class="ghost" id="both">Przygotuj IG + FB</button><button class="ghost" id="retry">Ponów wybrany kanał</button><button class="ghost" id="music">Muzyka dobrana</button><button class="ghost" id="verify">Sprawdź platformy</button><button class="ghost" id="hostinger">Wyślij paczki na Hostinger</button></div><div id="capabilities">Odczytuję HD, muzykę i adapter…</div>`;p.querySelectorAll('.manual').forEach(b=>b.onclick=()=>manualCheck(c,b.dataset.channel,b.dataset.checked==='true'));p.querySelectorAll('.prepare').forEach(b=>b.onclick=()=>prepare(c,b.dataset.channel,false));$('#phone').onclick=()=>phone(c);$('#both').onclick=()=>prepare(c,'obie',false);$('#retry').onclick=()=>prepare(c,state.channel,true);$('#music').onclick=()=>action(c,'music-ready',{});$('#verify').onclick=()=>action(c,'verify',{});$('#hostinger').onclick=publishHostinger;api(`/api/publications/${encodeURIComponent(c.post_id)}/capabilities`).then(x=>$('#capabilities').textContent=`HD: ${x.hd.etykieta||x.hd.stan} · Muzyka: ${x.awaiting_music?'czeka na wybór':'nie czeka'} · ${x.is_carousel?'karuzela':'rolka'} · końcowe kliknięcie: ręczne`).catch(e=>$('#capabilities').textContent=e.message)}
if(state.tab==='history'){p.innerHTML=c.history.length?c.history.slice().reverse().map(h=>`<div class="history-item"><b>${esc(h.co||'Zmiana')}</b><small>${esc(h.kiedy||'')}</small><span class="meta">${esc(h.szczegol||'')}</span></div>`).join(''):'<p class="meta">Brak zapisanej historii.</p>'}}

async function saveContent(c,approve){try{const fresh=await post(`/api/publications/${encodeURIComponent(c.post_id)}/content`,{expected_revision:c.revision,description:$('#description').value,hashtags:$('#hashtags').value,location:$('#location').value,approve});Object.assign(c,fresh);toast('Treść zapisana i ponownie odczytana.');renderDetail()}catch(e){if(e.status===409)toast('Konflikt wersji — tekst pozostał w edytorze. Odśwież kartę przed zapisem.');else toast(e.message)}}
async function phone(c){try{const r=await post(`/api/publications/${encodeURIComponent(c.post_id)}/phone-package`,{channel:'instagram'});location.href=r.url;toast('Paczka telefonu jest gotowa.');if(state.hostinger.enabled&&state.hostinger.configured)await publishHostinger()}catch(e){toast(e.message)}}
async function publishHostinger(){try{toast('Wysyłam paczki na Hostinger…');const r=await post('/api/mobile-packages/publish',{});toast(`Hostinger: wysłano ${r.uploaded} plików, bez zmian ${r.skipped}. Telefon widzi paczkę po odświeżeniu.`)}catch(e){toast(e.message)}}
function importPhoneEvents(){const input=document.createElement('input');input.type='file';input.accept='application/json,.json';input.onchange=async()=>{try{const payload=JSON.parse(await input.files[0].text());const r=await post('/api/mobile-events/import',payload);toast(`Import z telefonu: przyjęto ${r.accepted}, pominięto ${r.skipped} (duplikaty lub nieznane).`)}catch(e){toast(e.message)}};input.click()}
async function manualCheck(c,channel,checked){try{const fresh=await post(`/api/publications/${encodeURIComponent(c.post_id)}/manual-check`,{channel,checked,expected_revision:c.revision});Object.assign(c,fresh);toast(checked?'Zapisano Twój haczyk.':'Cofnięto Twój haczyk.');renderDetail()}catch(e){toast(e.message)}}
async function prepare(c,channel,retry){try{await post(`/api/publications/${encodeURIComponent(c.post_id)}/prepare-publication`,{channel,retry});toast('Formularz przygotowany. Końcowe kliknięcie wykonujesz ręcznie.')}catch(e){toast(e.message)}}
async function action(c,name,body){try{await post(`/api/publications/${encodeURIComponent(c.post_id)}/${name}`,body);toast('Operacja wykonana. Odświeżam stan.');await load()}catch(e){toast(e.message)}}
async function primary(c){if(c.next_action.code==='phone_package')return phone(c);state.tab=['finish','review_content'].includes(c.next_action.code)?'content':c.next_action.code==='show_history'?'history':'publish';renderDetail()}
async function post(path,body){return api(path,{method:'POST',body:JSON.stringify(body)})}
async function load(){const btn=$('#refresh');btn.classList.add('spin');try{const health=await api('/api/health');$('#healthDot').className='led '+(health.writes?'ok':'');$('#mode').textContent=health.writes?'Tryb produkcyjny':'Bezpieczny podgląd';state.hostinger=health.hostinger||{};$('#queue').textContent=(health.publication?'Publikowanie dostępne':'Publikowanie zablokowane')+' · Hostinger: '+(state.hostinger.enabled&&state.hostinger.configured?'połączony':'nieskonfigurowany');const data=await api(`/api/publications?brand=all&archive=true&channel=${state.channel}`);state.cards=data.items;render()}catch(e){$('#healthDot').className='led bad';$('#rows').innerHTML=`<div class="error">${esc(e.message)}</div>`}finally{btn.classList.remove('spin')}}
function shell(title,kicker='BYKU.PUBLIKACJE'){$('#sectionTitle').textContent=title;$('#sectionKicker').textContent=kicker}
function scheduledCards(){return state.cards.filter(c=>!c.archived&&brandMatch(c)).sort((a,b)=>(a.local_target_at||'9999').localeCompare(b.local_target_at||'9999'))}

// Zegar operatora i odliczanie do najbliższej publikacji — Zasada 15 minut.
function tick(){const now=new Date();$('#clock').textContent=`${pad(now.getHours())}:${pad(now.getMinutes())}:${pad(now.getSeconds())}`;$('#today').textContent=`${DAYS[now.getDay()]} ${pad(now.getDate())}.${pad(now.getMonth()+1)}.${now.getFullYear()}`;const next=state.cards.filter(c=>!c.archived&&brandMatch(c)&&c.next_action.code!=='done').map(c=>[c,when(c.local_target_at)]).filter(([,d])=>d&&d>now).sort((a,b)=>a[1]-b[1])[0];const box=$('#tminus');if(!next){box.className='tminus';$('#tminusValue').textContent='T−--:--:--';$('#tminusName').textContent='Brak terminów w kolejce';return}const s=Math.floor((next[1]-now)/1000),h=Math.floor(s/3600),dd=Math.floor(h/24);$('#tminusValue').textContent=dd>=1?`T−${dd}d ${pad(h%24)}:${pad(Math.floor(s%3600/60))}`:`T−${pad(h)}:${pad(Math.floor(s%3600/60))}:${pad(s%60)}`;$('#tminusName').textContent=next[0].name;box.className='tminus '+(s<=900?'hot':'armed')}

async function calendarView(){shell('Kalendarz publikacji','Plan dnia, tygodnia, miesiąca i lista');$('#summary').innerHTML='';$('#filters').innerHTML=`<button class="filter active" data-mode="week">Tydzień</button><button class="filter" data-mode="day">Dzień</button><button class="filter" data-mode="month">Miesiąc</button><button class="filter" data-mode="list">Lista</button><span class="sep"></span><button class="ghost" id="propose">Rozłóż szkice</button><button class="ghost" id="undo">Cofnij zmianę</button>`;const cards=scheduledCards();const days=[...new Set(cards.map(c=>(c.local_target_at||'Bez terminu').slice(0,10)))];const todayKey=new Date().toISOString().slice(0,10);const head=day=>{const d=when(day+' 00:00');return d?`${pad(d.getDate())}.${pad(d.getMonth()+1)} <small>${DAYS[d.getDay()]}</small>`:`— <small>Bez terminu</small>`};$('#rows').innerHTML=`<div class="calendar-grid">${days.map(day=>`<section class="calendar-day ${day===todayKey?'today':''}" data-day="${esc(day)}"><h3>${head(day)}</h3>${cards.filter(c=>(c.local_target_at||'Bez terminu').startsWith(day)).map(c=>`<article draggable="true" class="${esc(c.brand)}" data-id="${esc(c.post_id)}"><small>${esc((c.local_target_at||'').slice(11)||'--:--')} · ${esc(c.brand.toUpperCase())}</small><b>${esc(c.name)}</b></article>`).join('')}</section>`).join('')}</div>`;$('#detail').classList.remove('open');$('#detail').innerHTML='<div class="empty"><b>Przeciągnij kartę</b><span>Upuść na dzień, aby ustawić termin 18:45. Każdą zmianę można cofnąć.</span></div>';document.querySelectorAll('[draggable]').forEach(x=>x.ondragstart=e=>e.dataTransfer.setData('text/plain',x.dataset.id));document.querySelectorAll('.calendar-day').forEach(x=>{x.ondragover=e=>{e.preventDefault();x.classList.add('over')};x.ondragleave=()=>x.classList.remove('over');x.ondrop=async e=>{e.preventDefault();x.classList.remove('over');const id=e.dataTransfer.getData('text/plain'),c=state.cards.find(x=>x.post_id===id);if(!c||x.dataset.day==='Bez termin')return;try{await post('/api/schedule/apply',{changes:[{post_id:id,before:c.local_target_at,after:`${x.dataset.day} 18:45`}]});await load()}catch(err){toast(err.message)}}});$('#undo').onclick=async()=>{try{await post('/api/schedule/undo',{});await load();toast('Cofnięto ostatnią zmianę kalendarza.')}catch(e){toast(e.message)}};$('#propose').onclick=async()=>{const r=await api(`/api/schedule/proposals?brand=${state.brand==='all'?'atlet':state.brand}`);const v=r.variants.find(x=>x.id==='regular');if(!v)return toast('Brak propozycji do rozłożenia.');if(confirm(`Ustawić ${v.changes.length} terminów w wariancie regularnym?`)){await post('/api/schedule/apply',{changes:v.changes});await load()}}}
async function generatorView(){shell('Opisy i styl','Pełny Generator i edycja wersji');$('#summary').innerHTML=`<div class="metric wide hot"><strong>ATLET / RIGGER</strong><span>Generator zapisuje bezpośrednio do tej samej kolejki Studio.</span><button class="action" id="generator">Otwórz pełny Generator →</button></div>`;$('#filters').innerHTML='<span class="meta">Wybierz kartę poniżej, aby edytować opis, hashtagi i lokalizację albo zaakceptować wersję.</span>';renderRows();renderDetail();$('#generator').onclick=async()=>{try{await post('/api/generator/open',{brand:state.brand==='all'?'atlet':state.brand});toast('Generator został uruchomiony i podłączony do wspólnej kolejki.')}catch(e){toast(e.message)}}}
async function learningView(){shell('Uczenie','Reguły stylu, procesu i propozycje kodu');$('#summary').innerHTML='';$('#filters').innerHTML=`<button class="action" id="newLesson">+ Dodaj lekcję procesu</button><button class="ghost" id="importPhone">Import z telefonu</button><button class="ghost" id="refreshLearning">Odśwież</button>`;$('#importPhone').onclick=importPhoneEvents;$('#detail').classList.remove('open');$('#detail').innerHTML='<div class="empty"><b>System się uczy</b><span>Tylko jawne reguły. Każdą można aktywować po teście i cofnąć.</span></div>';const data=await api('/api/learning');$('#rows').innerHTML=`<div class="learning"><div class="col"><h3>// Reguły i propozycje</h3>${data.lessons.map(x=>`<article class="${esc(x.status)}"><b>${esc(x.kind)} · ${esc((x.brand||'global').toUpperCase())} · v${x.version} · ${esc(x.status)}</b><span>${esc(x.problem)}</span><small>${esc(x.solution||'Brak rozwiązania')}</small>${x.status==='draft'?`<button class="ghost activate" data-id="${x.lesson_id}">Aktywuj po teście</button>`:''}${x.status==='active'?`<button class="ghost revert" data-id="${x.lesson_id}">Cofnij</button>`:''}</article>`).join('')||'<p>Brak lekcji.</p>'}</div><div class="col"><h3>// Zdarzenia</h3>${data.events.slice(0,30).map(x=>`<article><b>${esc(x.brand||'global')} · ${esc(x.occurred_at)}</b><span>${esc(x.stage)}</span></article>`).join('')||'<p>Brak zdarzeń.</p>'}</div></div>`;$('#refreshLearning').onclick=learningView;$('#newLesson').onclick=async()=>{const problem=prompt('Jaki problem procesu został potwierdzony?');if(!problem)return;const solution=prompt('Jakie rozwiązanie proponujesz?')||'';await post('/api/learning/lessons',{kind:'process',brand:state.brand==='all'?null:state.brand,problem,solution,evidence:['jawna obserwacja użytkownika'],test:{status:'do_sprawdzenia'}});await learningView()};document.querySelectorAll('.activate').forEach(b=>b.onclick=async()=>{await post(`/api/learning/lessons/${b.dataset.id}/status`,{status:'active'});await learningView()});document.querySelectorAll('.revert').forEach(b=>b.onclick=async()=>{await post(`/api/learning/lessons/${b.dataset.id}/status`,{status:'reverted'});await learningView()})}
function freeMode(on){document.querySelector('.workspace').classList.toggle('free',on)}
function closeDetail(){state.selected=null;document.querySelectorAll('#rows .row.selected').forEach(r=>r.classList.remove('selected'));renderDetail()}
function render(){tick();freeMode(['calendar','learning'].includes(state.view));if(state.view==='calendar')return calendarView().catch(e=>toast(e.message));if(state.view==='style')return generatorView().catch(e=>toast(e.message));if(state.view==='learning')return learningView().catch(e=>toast(e.message));shell(state.view==='archive'?'Archiwum':state.view==='publications'?'Publikacje':state.view==='library'?'Biblioteka publikacji':state.view==='finish'?'Do dokończenia':'Stół publikacji',state.view==='today'?'Praca na dziś':'BYKU.PUBLIKACJE');renderSummary();renderFilters();renderRows();renderDetail()}

// Skróty operatora: / szukaj · J/K następna/poprzednia karta · R odśwież · Esc zamknij panel.
document.addEventListener('keydown',e=>{const typing=/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName);if(e.key==='Escape'){if(typing)return e.target.blur();return closeDetail()}if(typing||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='/'){e.preventDefault();return $('#search').focus()}if(e.key==='r'||e.key==='R')return load();if(e.key==='j'||e.key==='k'){const rows=[...document.querySelectorAll('#rows .row')];if(!rows.length)return;const i=rows.findIndex(r=>r.dataset.id===state.selected);const n=rows[Math.max(0,Math.min(rows.length-1,i<0?0:i+(e.key==='j'?1:-1)))];select(n.dataset.id);n.scrollIntoView({block:'nearest',behavior:'smooth'})}});
$('#brandSeg').onclick=e=>{const b=e.target.closest('button');if(!b)return;state.brand=b.dataset.brand;brandSeg();render()};$('#search').oninput=renderRows;$('#refresh').onclick=load;nav();brandSeg();tick();setInterval(tick,1000);load();
