import { appendUniqueEvent, composeCaption, createEvent, displayTitle, instagramUrl, isVideo, packageProgress, parseTarget, pickMedia, relativeTarget, resolveFileUrl, sha256Hex, sortPackages, unsyncedEvents } from "./domain.js";
import { createStore } from "./store.js";
import { pingDesktop, refreshPackages, sendEvents } from "./sync.js";

const APP_VERSION = "2026.09.27-2";
const store=createStore(), $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let settings=store.settings(), manifests=store.manifests(), events=store.events(), syncedIds=store.syncedIds(), syncResults=[], current=null, link={state:"checking",packages:0,sync:{}}, lastRefresh=0, flushTimer=null, swReg=null, pcSyncTimer=null;
const syncNames={current:"Aktualne",newer:"Nowe paczki",incomplete:"Niekompletna paczka",incompatible:"Niezgodna paczka",offline:"Brak połączenia"};
const tagNames={newer:"Nowa",incomplete:"Niekompletna",incompatible:"Niezgodna"};
const eventNames={downloaded:"Zapisano materiał w telefonie",description_copied:"Skopiowano opis",hashtags_copied:"Skopiowano hashtagi",instagram_opened:"Otwarto Instagram",sent:"Udostępniono do Instagrama",manual_hook:"Opublikowane — haczyk Instagram"};
const DAYS=["NDZ","PON","WT","ŚR","CZW","PT","SOB"],pad=n=>String(n).padStart(2,"0");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const plural=(n,one,few,many)=>n===1?one:(n%10>=2&&n%10<=4&&(n%100<10||n%100>=20))?few:many;

function manifestStatus(m){return syncResults.find(x=>x.key===`${m.post_id}::${m.brand}`)?.state||"current"}
function fileUrl(m,name){return resolveFileUrl(m._manifest_url,name)}
function whenText(m){const d=parseTarget(m.target_at);if(!d)return{txt:"Bez terminu",rel:"",tone:"none"};return{txt:`${DAYS[d.getDay()]} ${pad(d.getDate())}.${pad(d.getMonth()+1)} · ${pad(d.getHours())}:${pad(d.getMinutes())}`,...relativeTarget(d)}}
function whenHtml(w){return `<span class="when ${w.tone}"><span>${esc(w.txt)}</span>${w.rel?`<b>${esc(w.rel)}</b>`:""}</span>`}
function kindText(m){const media=pickMedia(m.files);return isVideo(media[0]?.name)?"Rolka":media.length>1?`Karuzela · ${media.length}`:"Zdjęcie"}
function kindShort(m){const media=pickMedia(m.files);return isVideo(media[0]?.name)?"Rolka":media.length>1?`${media.length} ${plural(media.length,"slajd","slajdy","slajdów")}`:"Foto"}
function thumbFor(m){const media=pickMedia(m.files);return m.files.some(x=>x.name==="miniaturka.png")?"miniaturka.png":media.find(x=>!isVideo(x.name))?.name}
function progressDots(p){return[["caption","Podpis"],["media","Materiał"],["published","Publikacja"]].map(([k,n])=>`<i class="${p[k]?"on":""}">${n}</i>`).join("")}

// ── Lista paczek ──
function renderPackages(){const list=$("#packageList"),rows=sortPackages(manifests.filter(x=>x.brand===settings.brand)).sort((a,b)=>packageProgress(events,a).published-packageProgress(events,b).published);const open=rows.filter(m=>!packageProgress(events,m).published).length;$("#packCount").textContent=open;list.innerHTML="";
if(!rows.length){list.innerHTML=`<div class="empty"><b>Pusto</b><span>${link.state==="ok"?"Na komputerze nie ma paczek tej marki. Desktop: Publikowanie → „Paczka na telefon”.":"Brak zapisanych paczek. Połącz się z komputerem i odśwież."}</span></div>`;return}
let nextMarked=false;rows.forEach((m,i)=>{const node=$("#packageTemplate").content.cloneNode(true),card=node.querySelector(".card"),img=node.querySelector("img"),w=whenText(m),p=packageProgress(events,m),state=p.published?"done":manifestStatus(m),thumb=thumbFor(m);
card.dataset.state=state;card.style.setProperty("--i",Math.min(i,10));
if(!p.published&&!nextMarked){card.classList.add("next");nextMarked=true}
img.src=thumb?fileUrl(m,thumb):"icon.svg";img.onerror=()=>{img.onerror=null;img.src="icon.svg";img.classList.add("fallback")};
node.querySelector(".kind").textContent=kindShort(m);
const tag=p.published?"Opublikowane":card.classList.contains("next")?"Następna":tagNames[state]||"";const tagEl=node.querySelector(".tag");tagEl.textContent=tag;tagEl.hidden=!tag;
node.querySelector(".title").textContent=displayTitle(m);node.querySelector(".meta").innerHTML=whenHtml(w);node.querySelector(".progress").innerHTML=progressDots(p);
node.querySelector(".card-open").onclick=()=>openPackage(m);list.append(node)})}

// ── Czynności: zapis lokalny + automatyczna wysyłka do komputera ──
function saveEvent(type,m,extra={}){events=appendUniqueEvent(events,createEvent(type,m,extra));store.saveEvents(events);renderEvents();clearTimeout(flushTimer);flushTimer=setTimeout(flushEvents,400)}
async function flushEvents(manual=false){const pending=unsyncedEvents(events,syncedIds);if(!pending.length){if(manual)$("#exportStatus").textContent="Nie ma nic do wysłania — komputer ma wszystko.";return}try{const r=await sendEvents(pending);syncedIds=[...new Set([...syncedIds,...pending.map(e=>e.event_id)])];store.saveSyncedIds(syncedIds);setLink("ok");if(manual)$("#exportStatus").textContent=`Komputer przyjął ${r.accepted}, pominął ${r.skipped} (już je miał).`}catch(e){if(manual)$("#exportStatus").textContent=`Nie udało się: ${e.message}. Spróbuj, gdy komputer będzie włączony, albo użyj „Plik”.`}renderEvents()}
function renderEvents(){const pending=unsyncedEvents(events,syncedIds),done=new Set(syncedIds),badge=$("#pendingBadge");badge.hidden=!pending.length;badge.textContent=pending.length;
$("#eventsCard").dataset.state=pending.length?"pending":"ok";$("#sendEvents").classList.toggle("primary",!!pending.length);$("#eventsSyncTitle").textContent=pending.length?`${pending.length} ${plural(pending.length,"czynność czeka","czynności czekają","czynności czeka")}`:"Wszystko w komputerze";$("#eventsSyncDetail").textContent=pending.length?(link.state==="ok"?"Wysyłam przy następnej okazji — możesz też wysłać teraz.":"Komputer niedostępny. Wyślą się same, gdy wróci połączenie."):"Każda czynność leci do desktopu od razu po wykonaniu.";
$("#eventList").innerHTML=events.length?events.slice().reverse().map(e=>{const m=manifests.find(x=>x.post_id===e.post_id&&x.brand===e.brand);return `<div class="event ${done.has(e.event_id)?"synced":"pending"}"><strong>${esc(eventNames[e.type]||e.type)}</strong><span>${esc(m?displayTitle(m):e.post_id)}</span><small>${esc(e.brand?.toUpperCase())} · ${new Date(e.occurred_at).toLocaleString("pl-PL",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})} · ${done.has(e.event_id)?"w komputerze ✓":"czeka"}</small></div>`}).join(""):'<div class="empty"><b>Brak czynności</b><span>Pojawią się, gdy skopiujesz podpis, udostępnisz materiał albo potwierdzisz publikację.</span></div>'}
async function exportEvents(){const status=$("#exportStatus");if(!events.length){status.textContent="Brak czynności do eksportu.";return}const payload={schema_version:1,source:"mobile",exported_at:new Date().toISOString(),events};const name=`byku-czynnosci-${new Date().toISOString().slice(0,19).replace(/[:T]/g,"-")}.json`;const file=new File([JSON.stringify(payload,null,2)],name,{type:"application/json"});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:"BYKU — czynności telefonu"})}else{const a=document.createElement("a");a.href=URL.createObjectURL(file);a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}status.textContent=`Zapisano ${events.length} czynności do pliku. Desktop: Uczenie → „Import z telefonu”. Duplikaty są pomijane.`}catch(e){if(e.name!=="AbortError")status.textContent=`Eksport nie powiódł się: ${e.message}`}}

// ── Połączenie z komputerem ──
function setLink(state,packages,sync){link={state,packages:packages??link.packages,sync:sync??link.sync};const b=$("#linkBadge");b.dataset.state=state;$("#linkText").textContent={ok:"Połączony",down:"Niedostępny",offline:"Bez sieci",checking:"Łączę…"}[state];renderFacts()}
async function checkLink(){if(!navigator.onLine)return setLink("offline");try{const r=await pingDesktop();const wasRunning=link.sync?.running;setLink("ok",r.packages,r.sync||{});if(unsyncedEvents(events,syncedIds).length)flushEvents();
// Komputer właśnie czyta kalendarze — pokazujemy to i odświeżamy paczki, gdy skończy.
clearTimeout(pcSyncTimer);if(r.sync?.running){if(!$("#syncPanel").classList.contains("busy"))setSync("newer","Komputer aktualizuje","Czyta kalendarze TikTok i Meta…");pcSyncTimer=setTimeout(checkLink,5000)}else if(wasRunning)refresh()}catch{setLink("down")}}
function ago(iso){if(!iso)return"nigdy";const m=Math.round((Date.now()-new Date(iso))/60000);if(isNaN(m))return"—";if(m<1)return"przed chwilą";if(m<60)return`${m} min temu`;if(m<1440)return`${Math.floor(m/60)} h temu`;return`${Math.round(m/1440)} d temu`}
function renderFacts(){const el=$("#linkFacts");if(!el)return;const rows=[["Komputer",{ok:"połączony",down:"niedostępny — włącz PC i desktop",offline:"brak internetu w telefonie",checking:"sprawdzam…"}[link.state]],["Adres appki",location.origin],["Paczek na komputerze",link.state==="ok"?String(link.packages):"—"],["Komputer: kalendarze",link.state!=="ok"?"—":link.sync?.running?"aktualizuje teraz…":ago(link.sync?.finished_at)],["Wersja appki",APP_VERSION]];el.innerHTML=rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join("")}

// ── Szczegóły paczki: 4 kroki do Instagrama ──
async function getText(m,name,signal){const r=await fetch(fileUrl(m,name),{signal});if(!r.ok)throw Error(`${name}: HTTP ${r.status}`);return r.text()}
// Pobiera plik z paskiem postępu i sprawdza SHA-256 — dopiero wtedy wolno go udostępnić.
async function fetchVerified(m,file,signal,onProgress){const r=await fetch(fileUrl(m,file.name),{signal});if(!r.ok)throw Error(`${file.name}: HTTP ${r.status}`);const total=+r.headers.get("content-length")||0;let blob;if(r.body&&total){const reader=r.body.getReader(),parts=[];let got=0;for(;;){const{done,value}=await reader.read();if(done)break;parts.push(value);got+=value.length;onProgress(got/total)}blob=new Blob(parts,{type:r.headers.get("content-type")||""})}else blob=await r.blob();if(await sha256Hex(blob)!==file.sha256.toLowerCase())throw Error(`${file.name}: suma SHA-256 jest niezgodna — odśwież paczki`);const type=blob.type&&blob.type!=="application/octet-stream"?blob.type:/\.mp4$/i.test(file.name)?"video/mp4":/\.mov$/i.test(file.name)?"video/quicktime":/\.png$/i.test(file.name)?"image/png":/\.webp$/i.test(file.name)?"image/webp":"image/jpeg";return new File([blob],file.name,{type})}
function stepDone(key,on=true){current?.root.querySelector(`[data-step="${key}"]`)?.classList.toggle("done",on)}
function say(text){const el=$("#detailStatus");if(el){el.textContent=text;el.classList.remove("flash");void el.offsetWidth;el.classList.add("flash")}}
async function prepareMedia(m,signal){const media=pickMedia(m.files),bar=$("#mediaBar"),label=$("#mediaLabel");const files=[];try{for(const [i,f] of media.entries()){label.textContent=`Pobieram ${i+1}/${media.length} · ${f.name}`;files.push(await fetchVerified(m,f,signal,k=>{bar.style.width=`${Math.round((i+k)/media.length*100)}%`}));bar.style.width=`${Math.round((i+1)/media.length*100)}%`}bar.style.width="100%";current.files=files;const canShare=!!navigator.canShare?.({files});const mb=files.reduce((s,f)=>s+f.size,0)/1048576;label.textContent=`Gotowe · ${files.length} ${plural(files.length,"plik","pliki","plików")} · ${mb.toFixed(1)} MB · SHA-256 zgodne`;$("#mediaStep").classList.add("ready");$("#shareMedia").disabled=!canShare;$("#saveMedia").disabled=false;if(!canShare){$("#shareMedia").hidden=true;$("#saveMedia").classList.add("primary","grow")}}catch(e){if(e.name==="AbortError")return;label.textContent=`Błąd: ${e.message}`;$("#mediaStep").classList.add("error")}}
async function prepareCaption(m,signal){const box=$("#captionBox");try{const names=new Set(m.files.map(f=>f.name));const [desc,tags]=await Promise.all([names.has("opis-do-skopiowania.txt")?getText(m,"opis-do-skopiowania.txt",signal):"",names.has("hashtagi.txt")?getText(m,"hashtagi.txt",signal):""]);current.desc=desc.trim();current.tags=tags.trim();current.caption=names.has("podpis.txt")?(await getText(m,"podpis.txt",signal)).trim():composeCaption(desc,tags);box.textContent=current.caption||"(pusty podpis)";box.classList.remove("loading");const n=current.caption.length;const count=$("#captionCount");count.textContent=`${n} / 2200`;count.classList.toggle("over",n>2200);$$("[data-copy]").forEach(b=>b.disabled=false)}catch(e){if(e.name!=="AbortError"){box.textContent=`Nie udało się wczytać podpisu: ${e.message}`;box.classList.remove("loading")}}}
// Kopiowanie synchronicznie w kliknięciu (tekst jest już w pamięci); gdy schowek odmówi — zaznaczamy tekst do ręcznego skopiowania.
async function copyText(text,label,m,types,btn){try{await navigator.clipboard.writeText(text);types.forEach(t=>saveEvent(t,m));stepDone("caption");const was=btn.textContent;btn.textContent="Skopiowano ✓";btn.classList.add("copied");setTimeout(()=>{btn.textContent=was;btn.classList.remove("copied")},1600);say(`${label} w schowku. W Instagramie przytrzymaj pole podpisu → Wklej.`)}catch{const box=$("#captionBox");const range=document.createRange();range.selectNodeContents(box);const sel=getSelection();sel.removeAllRanges();sel.addRange(range);say("Schowek zablokowany — tekst jest zaznaczony, stuknij „Kopiuj” w menu telefonu.")}}
async function shareMedia(m){try{await navigator.share({files:current.files,title:displayTitle(m)});saveEvent("sent",m,{via:"share",files:current.files.map(f=>f.name)});stepDone("media");say("Wybrane w Instagramie? Dodaj muzykę, wklej podpis i publikuj.")}catch(e){if(e.name!=="AbortError")say(`Udostępnianie nie powiodło się: ${e.message}. Użyj „Zapisz”.`)}}
function saveMedia(m){for(const f of current.files){const a=document.createElement("a");a.href=URL.createObjectURL(f);a.download=f.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),4000)}saveEvent("downloaded",m,{files:current.files.map(f=>f.name)});stepDone("media");say("Zapisane w telefonie (folder Pobrane) — Instagram widzi je w galerii.")}
function openPackage(m){current?.abort.abort();const detail=$("#packageDetail"),media=pickMedia(m.files),video=media.find(x=>isVideo(x.name)),p=packageProgress(events,m),w=whenText(m),thumb=thumbFor(m);
const preview=video?`<div class="hero-wrap"><video class="hero" controls playsinline preload="metadata" ${thumb?`poster="${esc(fileUrl(m,thumb))}"`:""} src="${esc(fileUrl(m,video.name))}"></video></div>`:`<div class="slides">${media.map((x,i)=>`<figure><img src="${esc(fileUrl(m,x.name))}" alt="Slajd ${i+1}" loading="lazy"><figcaption>${pad(i+1)}</figcaption></figure>`).join("")}</div>`;
detail.innerHTML=`<header class="detail-head"><p class="kicker">// ${esc(m.brand.toUpperCase())} · Instagram · ${esc(kindText(m))}</p><h2 id="detailTitle">${esc(displayTitle(m))}</h2>${whenHtml(w)}</header>${preview}
<ol class="steps">
<li data-step="caption" class="${p.caption?"done":""}"><div class="step-head"><span class="num">1</span><b>Skopiuj podpis</b><small id="captionCount" class="count"></small></div><pre id="captionBox" class="copybox loading">Wczytuję podpis…</pre><div class="row"><button class="action primary grow" data-copy="caption" disabled>Kopiuj podpis</button><button class="action" data-copy="desc" disabled>Opis</button><button class="action" data-copy="tags" disabled aria-label="Kopiuj hashtagi">#</button></div></li>
<li data-step="media" id="mediaStep" class="${p.media?"done":""}"><div class="step-head"><span class="num">2</span><b>Wyślij materiał</b></div><div class="meter"><i id="mediaBar"></i></div><small id="mediaLabel" class="hint mono">Czekam…</small><div class="row"><button class="action primary grow" id="shareMedia" disabled>Udostępnij → Instagram</button><button class="action" id="saveMedia" disabled>Zapisz</button></div><small class="hint">W menu Androida wybierz Instagram (Rolka / Post). „Zapisz” = kopia w galerii.</small></li>
<li data-step="publish"><div class="step-head"><span class="num">3</span><b>W Instagramie</b></div><ol class="mini"><li>Dodaj muzykę</li><li>Przytrzymaj pole podpisu → Wklej</li><li>Udostępnij</li></ol><div class="row"><button class="action grow" id="openInstagram">Otwórz Instagram</button></div></li>
<li data-step="published" class="${p.published?"done":""}"><div class="step-head"><span class="num">4</span><b>Potwierdź publikację</b></div><div class="row"><button class="action grow ${p.published?"":"confirm"}" id="manualHook" ${p.published?"disabled":""}>${p.published?"Opublikowane ✓":"✓ Opublikowałem"}</button></div><small class="hint">Trafi do komputera jako Twój haczyk Instagram do zatwierdzenia.</small></li>
</ol><p id="detailStatus" class="status-line" aria-live="polite"></p><p class="note">Muzyka i końcowe „Udostępnij” zostają ręczne. Pobranie paczki nigdy nie zmienia haczyka, terminu ani statusu.</p>`;
current={m,root:detail,abort:new AbortController(),files:[],caption:"",desc:"",tags:""};const {signal}=current.abort;
detail.querySelectorAll("[data-copy]").forEach(b=>b.onclick=()=>{const k=b.dataset.copy;if(k==="caption")copyText(current.caption,"Podpis",m,["description_copied","hashtags_copied"],b);else if(k==="desc")copyText(current.desc,"Opis",m,["description_copied"],b);else copyText(current.tags,"Hashtagi",m,["hashtags_copied"],b)});
$("#shareMedia").onclick=()=>shareMedia(m);$("#saveMedia").onclick=()=>saveMedia(m);
$("#openInstagram").onclick=()=>{saveEvent("instagram_opened",m);location.href=instagramUrl(navigator.userAgent)};
$("#manualHook").onclick=()=>{saveEvent("manual_hook",m,{value:true});stepDone("published");const b=$("#manualHook");b.textContent="Opublikowane ✓";b.disabled=true;b.classList.remove("confirm");say("Zapisano. Komputer dostanie zgłoszenie publikacji do zatwierdzenia.");renderPackages()};
const dlg=$("#packageDialog");dlg.showModal();dlg.scrollTop=0;prepareCaption(m,signal);prepareMedia(m,signal)}

// ── Odświeżanie ──
async function refresh(){const btn=$("#refreshButton");if(btn.disabled)return;btn.disabled=true;$("#syncPanel").classList.add("busy");$("#syncTitle").textContent="Sprawdzam…";try{const result=await refreshPackages({indexUrl:settings.indexUrl,brand:settings.brand,existing:manifests});manifests=result.manifests;syncResults=result.results;store.saveManifests(manifests);store.saveLastSync({at:new Date().toISOString(),brand:settings.brand});lastRefresh=Date.now();const states=new Set(syncResults.map(x=>x.state)),state=states.has("incompatible")?"incompatible":states.has("incomplete")?"incomplete":states.has("newer")?"newer":"current";const n=syncResults.length,fresh=syncResults.filter(x=>x.state==="newer").length;setSync(state,state==="newer"?`${fresh} ${plural(fresh,"nowa paczka","nowe paczki","nowych paczek")}`:syncNames[state],`${n} ${plural(n,"paczka","paczki","paczek")} · ${new Date().toLocaleTimeString("pl-PL",{hour:"2-digit",minute:"2-digit"})}${link.sync?.running?" · komputer czyta kalendarze…":""}`);setLink("ok",n);renderPackages()}catch(e){const last=store.lastSync();setSync("offline",syncNames.offline,last?`Pokazuję odczyt z ${new Date(last.at).toLocaleString("pl-PL",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}`:e.message);checkLink();renderPackages()}finally{btn.disabled=false;$("#syncPanel").classList.remove("busy")}}
// Ręczne „odśwież wszystko”: paczki + połączenie z PC + zaległe czynności + nowa wersja appki.
async function refreshAll(){await Promise.all([refresh(),checkLink(),swReg?swReg.update().catch(()=>{}):null]);if(unsyncedEvents(events,syncedIds).length)await flushEvents()}
async function checkUpdate(){const st=$("#updateStatus");st.textContent="Sprawdzam…";if(!swReg){st.textContent="Aktualizacje działają po otwarciu appki z komputera (https).";return}try{await swReg.update();if(swReg.installing||swReg.waiting){st.textContent="Jest nowa wersja — instaluję i przeładuję appkę.";return}st.textContent=`Masz najnowszą wersję (${APP_VERSION}).`}catch(e){st.textContent=`Nie udało się sprawdzić: ${e.message}`}}
function setSync(state,title,detail){const p=$("#syncPanel");p.className=`sync-bar ${state}`;$("#syncTitle").textContent=title;$("#syncDetail").textContent=detail}

// ── Nawigacja i ustawienia ──
$$("nav button").forEach(b=>b.onclick=()=>{$$("nav button").forEach(x=>x.classList.toggle("active",x===b));$$(".view").forEach(x=>x.classList.remove("active"));$(`#${b.dataset.view}View`).classList.add("active");scrollTo({top:0})});
function brandSeg(){$$("#brandSeg button").forEach(b=>b.setAttribute("aria-checked",String(b.dataset.brand===settings.brand)))}
$("#brandSeg").onclick=e=>{const b=e.target.closest("button");if(!b||b.dataset.brand===settings.brand)return;settings={...settings,brand:b.dataset.brand};store.saveSettings(settings);brandSeg();renderPackages();refresh()};
$("#linkBadge").onclick=()=>{setLink("checking");checkLink()};
$("#sendEvents").onclick=()=>flushEvents(true);$("#exportEvents").onclick=exportEvents;
$("#indexUrl").value=settings.indexUrl;$("#saveSettings").onclick=()=>{settings={...settings,indexUrl:$("#indexUrl").value.trim()||"paczki/index.json"};store.saveSettings(settings);$("#indexUrl").value=settings.indexUrl;$("#settingsStatus").textContent="Zapisano na tym telefonie.";refresh()};
$("#refreshButton").onclick=refreshAll;$("#checkUpdate").onclick=checkUpdate;$("#closeDialog").onclick=()=>$("#packageDialog").close();
$("#packageDialog").addEventListener("click",e=>{if(e.target===e.currentTarget)e.currentTarget.close()});
$("#packageDialog").addEventListener("close",()=>{current?.abort.abort();current=null;renderPackages()});
window.addEventListener("online",()=>{checkLink();refresh()});window.addEventListener("offline",()=>setLink("offline"));
document.addEventListener("visibilitychange",()=>{if(document.visibilityState!=="visible")return;checkLink();if(Date.now()-lastRefresh>60000&&!$("#packageDialog").open)refresh()});
brandSeg();renderPackages();renderEvents();renderFacts();checkLink();refresh();

// Automatyczna aktualizacja appki: nowa wersja z komputera przejmuje stronę i przeładowuje ją raz (nigdy w trakcie otwartej paczki).
if("serviceWorker" in navigator)window.addEventListener("load",async()=>{const hadController=!!navigator.serviceWorker.controller;let reloading=false;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(!hadController||reloading)return;reloading=true;if($("#packageDialog").open){setSync("newer","Nowa wersja appki","Zamknij paczkę — przeładuję automatycznie.");$("#packageDialog").addEventListener("close",()=>location.reload(),{once:true})}else location.reload()});let reg;try{reg=await navigator.serviceWorker.register("sw.js");swReg=reg}catch{return}const check=()=>reg.update().catch(()=>{});setInterval(check,30*60*1000);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")check()})});
