import { appendUniqueEvent, createEvent, isSourceMedia, resolveFileUrl, sha256Hex, validateManifest } from "./domain.js";
import { createStore } from "./store.js";
import { refreshPackages } from "./sync.js";

const store=createStore(), $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let settings=store.settings(), manifests=store.manifests(), events=store.events(), syncResults=[];
const statusNames={current:"Aktualna",newer:"Jest nowsza wersja",incomplete:"Niekompletna",incompatible:"Niezgodna",offline:"Brak połączenia"};

function saveEvent(type,m,extra={}){events=appendUniqueEvent(events,createEvent(type,m,extra));store.saveEvents(events);renderEvents()}
function setSync(state,title,detail){const p=$("#syncPanel");p.className=`sync-panel ${state}`;$("#syncTitle").textContent=title;$("#syncDetail").textContent=detail}
function manifestStatus(m){return syncResults.find(x=>x.key===`${m.post_id}::${m.brand}`)?.state||"current"}
function mediaFiles(m){return m.files.filter(x=>isSourceMedia(x.name))}
function fileUrl(m,name){return resolveFileUrl(m._manifest_url,name)}
function renderPackages(){const list=$("#packageList"),rows=manifests.filter(x=>x.brand===settings.brand);list.innerHTML="";if(!rows.length){list.innerHTML='<div class="empty">Brak zapisanych paczek. Użyj przycisku odświeżania.</div>';return}for(const m of rows.sort((a,b)=>String(b.exported_at).localeCompare(String(a.exported_at)))){const node=$("#packageTemplate").content.cloneNode(true),media=mediaFiles(m),img=node.querySelector("img");img.src=fileUrl(m,m.files.find(x=>x.name==="miniaturka.png")?.name||media[0]?.name||"icon.svg");img.onerror=()=>img.src="icon.svg";node.querySelector(".title").textContent=m.post_id;node.querySelector(".meta").textContent=`${m.brand.toUpperCase()} · ${media.length} plik(ów) · ${m.content_revision.slice(0,12)}`;node.querySelector(".state").textContent=statusNames[manifestStatus(m)];node.querySelector(".card-open").onclick=()=>openPackage(m);list.append(node)}}
function renderEvents(){const list=$("#eventList");list.innerHTML=events.length?events.slice().reverse().map(e=>`<div class="event"><strong>${e.type}</strong>${e.post_id} · ${new Date(e.occurred_at).toLocaleString("pl-PL")}</div>`).join(""):'<div class="empty">Brak czynności. Import niczego tu nie dopisuje.</div>'}
async function getText(m,name){const r=await fetch(fileUrl(m,name));if(!r.ok)throw Error(`HTTP ${r.status}`);return r.text()}
async function copyField(m,name,type){try{const text=await getText(m,name);await navigator.clipboard.writeText(text.trim());saveEvent(type,m);$("#detailStatus").textContent="Skopiowano do schowka."}catch(e){$("#detailStatus").textContent=`Nie udało się skopiować: ${e.message}`}}
async function downloadOne(m,file){const r=await fetch(fileUrl(m,file.name));if(!r.ok)throw Error(`${file.name}: HTTP ${r.status}`);const blob=await r.blob(),actual=await sha256Hex(blob);if(actual!==file.sha256.toLowerCase())throw Error(`${file.name}: suma SHA-256 jest niezgodna`);const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=file.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
async function downloadMedia(m){const status=$("#detailStatus");try{for(const f of mediaFiles(m)){status.textContent=`Sprawdzam i pobieram: ${f.name}`;await downloadOne(m,f)}saveEvent("downloaded",m,{files:mediaFiles(m).map(x=>x.name)});status.textContent="Pobrano komplet źródeł, każda suma SHA-256 jest zgodna."}catch(e){status.textContent=`Przerwano: ${e.message}`}}
function openPackage(m){const detail=$("#packageDetail"),media=mediaFiles(m),video=media.find(x=>/\.(mp4|mov|webm|m4v)$/i.test(x.name));const preview=video?`<video class="hero" controls playsinline src="${fileUrl(m,video.name)}"></video>`:`<div class="slides">${media.map(x=>`<img src="${fileUrl(m,x.name)}" alt="Slajd">`).join("")}</div>`;detail.innerHTML=`<p class="kicker">${m.brand.toUpperCase()} · INSTAGRAM</p><h2>${m.post_id}</h2>${preview}<p class="status-line">Rewizja ${m.content_revision}<br>${new Date(m.exported_at).toLocaleString("pl-PL")}</p><div class="actions"><button class="action" id="downloadMedia">Pobierz film / slajdy</button><button class="action" id="copyDescription">Kopiuj opis</button><button class="action" id="copyHashtags">Kopiuj hashtagi</button><button class="action" id="openInstagram">Otwórz Instagram</button><button class="action wide" id="manualHook">✓ Ręcznie ustaw haczyk Instagram</button></div><p id="detailStatus" class="status-line"></p><p class="danger-note">Muzyka i końcowy klik publikacji pozostają ręczne. Import paczki nigdy nie zmienia haczyka, terminu ani statusu.</p>`;$("#downloadMedia").onclick=()=>downloadMedia(m);$("#copyDescription").onclick=()=>copyField(m,"opis-do-skopiowania.txt","description_copied");$("#copyHashtags").onclick=()=>copyField(m,"hashtagi.txt","hashtags_copied");$("#openInstagram").onclick=()=>{saveEvent("instagram_opened",m);location.href="https://www.instagram.com/"};$("#manualHook").onclick=()=>{saveEvent("manual_hook",m,{value:true});$("#detailStatus").textContent="Zapisano świadomą, ręczną operację haczyka dla Instagrama."};$("#packageDialog").showModal()}
async function refresh(){const btn=$("#refreshButton");btn.disabled=true;btn.textContent="Sprawdzam indeks i manifesty…";try{const result=await refreshPackages({indexUrl:settings.indexUrl,brand:settings.brand,existing:manifests});manifests=result.manifests;syncResults=result.results;store.saveManifests(manifests);store.saveLastSync({at:new Date().toISOString(),brand:settings.brand});const states=new Set(syncResults.map(x=>x.state)),state=states.has("incompatible")?"incompatible":states.has("incomplete")?"incomplete":states.has("newer")?"newer":"current";setSync(state,statusNames[state],`${syncResults.length} manifestów · ${new Date().toLocaleTimeString("pl-PL")}`);renderPackages()}catch(e){const last=store.lastSync();setSync("offline","Brak połączenia z ostatnim poprawnym odczytem",last?`Ostatnio: ${new Date(last.at).toLocaleString("pl-PL")} · ${e.message}`:e.message);renderPackages()}finally{btn.disabled=false;btn.textContent="↻ Odśwież i sprawdź zgodność"}}
function setOnline(){const b=$("#networkBadge");b.textContent=navigator.onLine?"ONLINE":"OFFLINE";b.classList.toggle("offline",!navigator.onLine)}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(x=>x.classList.remove('active'));$(`#${b.dataset.view}View`).classList.add('active')});
$("#brandSelect").value=settings.brand;$("#indexUrl").value=settings.indexUrl;$("#brandSelect").onchange=e=>{settings={...settings,brand:e.target.value};store.saveSettings(settings);renderPackages()};$("#saveSettings").onclick=()=>{settings={...settings,indexUrl:$("#indexUrl").value.trim()};store.saveSettings(settings);$("#settingsStatus").textContent="Zapisano lokalnie na tym urządzeniu."};$("#refreshButton").onclick=refresh;$("#closeDialog").onclick=()=>$("#packageDialog").close();window.addEventListener("online",setOnline);window.addEventListener("offline",setOnline);setOnline();renderPackages();renderEvents();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
