import { appendUniqueEvent, composeCaption, createEvent, instagramUrl, isSourceMedia, packageProgress, parseTarget, resolveFileUrl, sha256Hex, sortPackages } from "./domain.js";
import { createStore } from "./store.js";
import { refreshPackages } from "./sync.js";

const store=createStore(), $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let settings=store.settings(), manifests=store.manifests(), events=store.events(), syncResults=[];
const statusNames={current:"Aktualna",newer:"Nowa lub zaktualizowana",incomplete:"Niekompletna",incompatible:"Niezgodna",offline:"Brak połączenia"};
const eventNames={downloaded:"Zapisano materiał w telefonie",description_copied:"Skopiowano opis",hashtags_copied:"Skopiowano hashtagi",instagram_opened:"Otwarto Instagram",sent:"Udostępniono do Instagrama",manual_hook:"Opublikowane — haczyk Instagram"};
const DAYS=["NDZ","PON","WT","ŚR","CZW","PT","SOB"],pad=n=>String(n).padStart(2,"0");
let current=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));

function saveEvent(type,m,extra={}){events=appendUniqueEvent(events,createEvent(type,m,extra));store.saveEvents(events);renderEvents()}
function setSync(state,title,detail){const p=$("#syncPanel");p.className=`sync-panel ${state}`;$("#syncTitle").textContent=title;$("#syncDetail").textContent=detail}
function manifestStatus(m){return syncResults.find(x=>x.key===`${m.post_id}::${m.brand}`)?.state||"current"}
function mediaFiles(m){return m.files.filter(x=>isSourceMedia(x.name))}
function fileUrl(m,name){return resolveFileUrl(m._manifest_url,name)}
function whenText(m){const d=parseTarget(m.target_at);if(!d)return{txt:"Bez terminu",rel:"",cls:"none"};const min=Math.round((d-Date.now())/60000);const txt=`${DAYS[d.getDay()]} ${pad(d.getDate())}.${pad(d.getMonth()+1)} · ${pad(d.getHours())}:${pad(d.getMinutes())}`;if(min<0)return{txt,rel:"po terminie",cls:"late"};if(min<=15)return{txt,rel:`za ${min} min`,cls:"hot"};if(min<180)return{txt,rel:`za ${Math.floor(min/60)} h ${min%60} min`,cls:"soon"};return{txt,rel:min<1440?`za ${Math.floor(min/60)} h`:`za ${Math.round(min/1440)} d`,cls:""}}
function progressDots(p){return[["caption","Podpis"],["media","Materiał"],["published","Opublikowane"]].map(([k,n])=>`<i class="${p[k]?"on":""}" title="${n}">${n}</i>`).join("")}
function renderPackages(){const list=$("#packageList"),rows=sortPackages(manifests.filter(x=>x.brand===settings.brand)).sort((a,b)=>packageProgress(events,a).published-packageProgress(events,b).published);list.innerHTML="";if(!rows.length){list.innerHTML='<div class="empty">Brak zapisanych paczek. Użyj przycisku odświeżania.</div>';return}for(const m of rows){const node=$("#packageTemplate").content.cloneNode(true),media=mediaFiles(m),img=node.querySelector("img"),w=whenText(m),p=packageProgress(events,m);img.src=fileUrl(m,m.files.find(x=>x.name==="miniaturka.png")?.name||media.find(x=>!/\.(mp4|mov|webm|m4v)$/i.test(x.name))?.name||"icon.svg");img.onerror=()=>img.src="icon.svg";node.querySelector(".title").textContent=m.title||m.post_id;node.querySelector(".meta").innerHTML=`<span class="when ${w.cls}">${esc(w.txt)}${w.rel?` <b>${esc(w.rel)}</b>`:""}</span><span>${media.length>1?`Karuzela · ${media.length} slajdy`:/\.(mp4|mov|webm|m4v)$/i.test(media[0]?.name||"")?"Rolka":"Zdjęcie"}</span>`;const card=node.querySelector(".card");card.dataset.state=p.published?"done":manifestStatus(m);node.querySelector(".state").innerHTML=p.published?"Opublikowane ✓":esc(statusNames[manifestStatus(m)]);node.querySelector(".progress").innerHTML=progressDots(p);node.querySelector(".card-open").onclick=()=>openPackage(m);list.append(node)}}
function renderEvents(){const list=$("#eventList");list.innerHTML=events.length?events.slice().reverse().map(e=>`<div class="event"><strong>${esc(eventNames[e.type]||e.type)}</strong>${esc(e.brand?.toUpperCase())} · ${esc(e.post_id)} · ${new Date(e.occurred_at).toLocaleString("pl-PL")}</div>`).join(""):'<div class="empty">Brak czynności. Import niczego tu nie dopisuje.</div>'}
async function getText(m,name,signal){const r=await fetch(fileUrl(m,name),{signal});if(!r.ok)throw Error(`${name}: HTTP ${r.status}`);return r.text()}
// Pobiera plik z paskiem postępu i sprawdza SHA-256 — dopiero wtedy wolno go udostępnić.
async function fetchVerified(m,file,signal,onProgress){const r=await fetch(fileUrl(m,file.name),{signal});if(!r.ok)throw Error(`${file.name}: HTTP ${r.status}`);const total=+r.headers.get("content-length")||0;let blob;if(r.body&&total){const reader=r.body.getReader(),parts=[];let got=0;for(;;){const{done,value}=await reader.read();if(done)break;parts.push(value);got+=value.length;onProgress(got/total)}blob=new Blob(parts,{type:r.headers.get("content-type")||""})}else blob=await r.blob();if(await sha256Hex(blob)!==file.sha256.toLowerCase())throw Error(`${file.name}: suma SHA-256 jest niezgodna — odśwież paczki`);const type=blob.type&&blob.type!=="application/octet-stream"?blob.type:/\.mp4$/i.test(file.name)?"video/mp4":/\.mov$/i.test(file.name)?"video/quicktime":/\.png$/i.test(file.name)?"image/png":/\.webp$/i.test(file.name)?"image/webp":"image/jpeg";return new File([blob],file.name,{type})}
function stepDone(key,on=true){current?.root.querySelector(`[data-step="${key}"]`)?.classList.toggle("done",on)}
function say(text){const el=$("#detailStatus");if(el)el.textContent=text}
async function prepareMedia(m,signal){const media=mediaFiles(m),bar=$("#mediaBar"),label=$("#mediaLabel");const files=[];try{for(const [i,f] of media.entries()){label.textContent=`Przygotowuję ${i+1}/${media.length} · ${f.name}`;files.push(await fetchVerified(m,f,signal,k=>{bar.style.width=`${Math.round((i+k)/media.length*100)}%`}));bar.style.width=`${Math.round((i+1)/media.length*100)}%`}bar.style.width="100%";current.files=files;const canShare=!!navigator.canShare?.({files});label.textContent=`Gotowe · ${files.length} ${files.length>1?"pliki":"plik"} · SHA-256 zgodne`;$("#shareMedia").disabled=!canShare;$("#saveMedia").disabled=false;if(!canShare){$("#shareMedia").hidden=true;$("#saveMedia").classList.add("primary")}}catch(e){if(e.name==="AbortError")return;label.textContent=`Błąd: ${e.message}`;$("#mediaStep").classList.add("error")}}
async function prepareCaption(m,signal){const box=$("#captionBox");try{const names=new Set(m.files.map(f=>f.name));const [desc,tags]=await Promise.all([names.has("opis-do-skopiowania.txt")?getText(m,"opis-do-skopiowania.txt",signal):"",names.has("hashtagi.txt")?getText(m,"hashtagi.txt",signal):""]);current.desc=desc.trim();current.tags=tags.trim();current.caption=names.has("podpis.txt")?(await getText(m,"podpis.txt",signal)).trim():composeCaption(desc,tags);box.textContent=current.caption||"(pusty podpis)";$("#captionCount").textContent=`${current.caption.length} / 2200 znaków`;$$("[data-copy]").forEach(b=>b.disabled=false)}catch(e){if(e.name!=="AbortError")box.textContent=`Nie udało się wczytać podpisu: ${e.message}`}}
// Kopiowanie synchronicznie w kliknięciu (tekst jest już w pamięci); gdy schowek odmówi — zaznaczamy tekst do ręcznego skopiowania.
async function copyText(text,label,m,types){try{await navigator.clipboard.writeText(text);types.forEach(t=>saveEvent(t,m));stepDone("caption");say(`${label} w schowku. W Instagramie przytrzymaj pole podpisu → Wklej.`)}catch{const box=$("#captionBox");const range=document.createRange();range.selectNodeContents(box);const sel=getSelection();sel.removeAllRanges();sel.addRange(range);say("Schowek zablokowany — tekst jest zaznaczony, stuknij „Kopiuj” w menu telefonu.")}}
async function shareMedia(m){try{await navigator.share({files:current.files,title:m.title||m.post_id});saveEvent("sent",m,{via:"share",files:current.files.map(f=>f.name)});stepDone("media");say("Wybrane w Instagramie? Dodaj muzykę, wklej podpis i publikuj.")}catch(e){if(e.name!=="AbortError")say(`Udostępnianie nie powiodło się: ${e.message}. Użyj „Zapisz w telefonie”.`)}}
function saveMedia(m){for(const f of current.files){const a=document.createElement("a");a.href=URL.createObjectURL(f);a.download=f.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),4000)}saveEvent("downloaded",m,{files:current.files.map(f=>f.name)});stepDone("media");say("Zapisane w telefonie (folder Pobrane) — Instagram widzi je w galerii.")}
function openPackage(m){current?.abort.abort();const detail=$("#packageDetail"),media=mediaFiles(m),video=media.find(x=>/\.(mp4|mov|webm|m4v)$/i.test(x.name)),p=packageProgress(events,m),w=whenText(m);const preview=video?`<video class="hero" controls playsinline preload="metadata" src="${fileUrl(m,video.name)}"></video>`:`<div class="slides">${media.map((x,i)=>`<img src="${fileUrl(m,x.name)}" alt="Slajd ${i+1}">`).join("")}</div>`;
detail.innerHTML=`<p class="kicker">// ${esc(m.brand.toUpperCase())} · Instagram</p><h2>${esc(m.title||m.post_id)}</h2><p class="when ${w.cls}">${esc(w.txt)}${w.rel?` <b>${esc(w.rel)}</b>`:""}</p>${preview}
<ol class="steps">
<li data-step="caption" class="${p.caption?"done":""}"><div class="step-head"><span class="num">1</span><b>Skopiuj podpis</b></div><pre id="captionBox" class="copybox">Wczytuję podpis…</pre><small id="captionCount" class="hint"></small><div class="row"><button class="action primary grow" data-copy="caption" disabled>Kopiuj podpis</button><button class="action" data-copy="desc" disabled>Opis</button><button class="action" data-copy="tags" disabled>#</button></div></li>
<li data-step="media" id="mediaStep" class="${p.media?"done":""}"><div class="step-head"><span class="num">2</span><b>Wyślij materiał do Instagrama</b></div><div class="meter"><i id="mediaBar"></i></div><small id="mediaLabel" class="hint">Czekam…</small><div class="row"><button class="action primary grow" id="shareMedia" disabled>Udostępnij → Instagram</button><button class="action" id="saveMedia" disabled>Zapisz</button></div><small class="hint">W menu Androida wybierz Instagram (Rolka / Post). Zapisz = kopia w galerii.</small></li>
<li data-step="publish"><div class="step-head"><span class="num">3</span><b>W Instagramie</b></div><small class="hint">Dodaj muzykę → przytrzymaj pole podpisu → Wklej → Udostępnij.</small><div class="row"><button class="action grow" id="openInstagram">Otwórz Instagram</button></div></li>
<li data-step="published" class="${p.published?"done":""}"><div class="step-head"><span class="num">4</span><b>Potwierdź publikację</b></div><div class="row"><button class="action grow" id="manualHook">${p.published?"Opublikowane ✓":"✓ Opublikowałem — ustaw haczyk"}</button></div></li>
</ol><p id="detailStatus" class="status-line" aria-live="polite"></p><p class="danger-note">Muzyka i końcowy klik publikacji zostają ręczne. Import paczki nigdy nie zmienia haczyka, terminu ani statusu.</p>`;
current={m,root:detail,abort:new AbortController(),files:[],caption:"",desc:"",tags:""};const {signal}=current.abort;
detail.querySelectorAll("[data-copy]").forEach(b=>b.onclick=()=>{const k=b.dataset.copy;if(k==="caption")copyText(current.caption,"Podpis",m,["description_copied","hashtags_copied"]);else if(k==="desc")copyText(current.desc,"Opis",m,["description_copied"]);else copyText(current.tags,"Hashtagi",m,["hashtags_copied"])});
$("#shareMedia").onclick=()=>shareMedia(m);$("#saveMedia").onclick=()=>saveMedia(m);
$("#openInstagram").onclick=()=>{saveEvent("instagram_opened",m);location.href=instagramUrl(navigator.userAgent)};
$("#manualHook").onclick=()=>{saveEvent("manual_hook",m,{value:true});stepDone("published");$("#manualHook").textContent="Opublikowane ✓";say("Zapisano świadomy haczyk Instagram. Trafi do desktopu przy eksporcie czynności.");renderPackages()};
$("#packageDialog").showModal();prepareCaption(m,signal);prepareMedia(m,signal)}
async function refresh(){const btn=$("#refreshButton");btn.disabled=true;btn.textContent="Sprawdzam indeks i manifesty…";try{const result=await refreshPackages({indexUrl:settings.indexUrl,brand:settings.brand,existing:manifests});manifests=result.manifests;syncResults=result.results;store.saveManifests(manifests);store.saveLastSync({at:new Date().toISOString(),brand:settings.brand});const states=new Set(syncResults.map(x=>x.state)),state=states.has("incompatible")?"incompatible":states.has("incomplete")?"incomplete":states.has("newer")?"newer":"current";setSync(state,statusNames[state],`${syncResults.length} manifestów · ${new Date().toLocaleTimeString("pl-PL")}`);renderPackages()}catch(e){const last=store.lastSync();setSync("offline","Brak połączenia z ostatnim poprawnym odczytem",last?`Ostatnio: ${new Date(last.at).toLocaleString("pl-PL")} · ${e.message}`:e.message);renderPackages()}finally{btn.disabled=false;btn.textContent="↻ Odśwież i sprawdź zgodność"}}
function setOnline(){const b=$("#networkBadge");b.textContent=navigator.onLine?"ONLINE":"OFFLINE";b.classList.toggle("offline",!navigator.onLine)}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(x=>x.classList.remove('active'));$(`#${b.dataset.view}View`).classList.add('active')});
function brandSeg(){$$("#brandSeg button").forEach(b=>b.setAttribute("aria-checked",String(b.dataset.brand===settings.brand)))}
$("#brandSeg").onclick=e=>{const b=e.target.closest("button");if(!b)return;$("#brandSelect").value=b.dataset.brand;$("#brandSelect").dispatchEvent(new Event("change"))};
async function exportEvents(){const status=$("#exportStatus");if(!events.length){status.textContent="Brak czynności do eksportu.";return}const payload={schema_version:1,source:"mobile",exported_at:new Date().toISOString(),events};const name=`byku-czynnosci-${new Date().toISOString().slice(0,19).replace(/[:T]/g,"-")}.json`;const file=new File([JSON.stringify(payload,null,2)],name,{type:"application/json"});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:"BYKU — czynności telefonu"})}else{const a=document.createElement("a");a.href=URL.createObjectURL(file);a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}status.textContent=`Wyeksportowano ${events.length} czynności. Desktop pomija duplikaty, więc ponowny eksport jest bezpieczny.`}catch(e){if(e.name!=="AbortError")status.textContent=`Eksport nie powiódł się: ${e.message}`}}
$("#exportEvents").onclick=exportEvents;
$("#brandSelect").value=settings.brand;brandSeg();$("#indexUrl").value=settings.indexUrl;$("#brandSelect").onchange=e=>{settings={...settings,brand:e.target.value};store.saveSettings(settings);brandSeg();renderPackages()};$("#saveSettings").onclick=()=>{settings={...settings,indexUrl:$("#indexUrl").value.trim()};store.saveSettings(settings);$("#settingsStatus").textContent="Zapisano lokalnie na tym urządzeniu."};$("#refreshButton").onclick=refresh;$("#closeDialog").onclick=()=>$("#packageDialog").close();$("#packageDialog").addEventListener("close",()=>{current?.abort.abort();current=null;renderPackages()});window.addEventListener("online",setOnline);window.addEventListener("offline",setOnline);setOnline();renderPackages();renderEvents();
// Automatyczna aktualizacja: nowa wersja z Hostingera przejmuje stronę i przeładowuje ją raz (nigdy w trakcie otwartej paczki).
if("serviceWorker" in navigator)window.addEventListener("load",async()=>{const hadController=!!navigator.serviceWorker.controller;let reloading=false;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(!hadController||reloading)return;reloading=true;if($("#packageDialog").open){setSync("newer","Nowa wersja aplikacji","Zamknij paczkę — przeładuję automatycznie.");$("#packageDialog").addEventListener("close",()=>location.reload(),{once:true})}else location.reload()});let reg;try{reg=await navigator.serviceWorker.register("sw.js")}catch{return}const check=()=>reg.update().catch(()=>{});setInterval(check,30*60*1000);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")check()})});
